# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

source: source
destination: _site
sass:
  sass_dir: _sass
  style: expanded # compressed # expanded

# permalink and highlighter
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments

# SEO settings
title: Celso Mireles
description: "A place for thoughts and stuff."
keywords: "Web Development, Musician, blog, PHP, Javascript, Graphic Design, python, Jekyll"

# Site settings
url: http://celsomireles.com
baseurl: ""
# baseurl: ""

# Author settings
author:
  name      : Celso Mireles
  job       : Digital Strategy Consultant
  bio       : "UndocuTechie: Entrepreneur, Web Developer, Digital Strategist."
  thumb     : /images/author.jpg
  email     : celso.mireles@gmail.com
  url       : http://celsomireles.com
  github    : http://github.com/celsom3
  twitter   : http://twitter.com/celsom3
  facebook  : http://facebook.com/celso.mireles
  linkedin  : https://www.linkedin.com/in/celsomireles

google_analytics: UA-39494279-1
repo: https://github.com/celsom3/celsom3.github.io

# comments
disqus_shortname: "celsomireles"
